version: '3.3'
services:
  petclinic:
    image: mysql:9.1
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    entrypoint: ["java", "-Dspring.profiles.active=mysql", "-Dspring.datasource.url=${MYSQL_URL:-jdbc:mysql://petclinic/petclinic}", "-jar", "app.jar"]
    depends_on:
      - petclinic
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "app"
